[default]
DB_URL = 'localhost'
DB_PORT = 27017
DB_NAME = 'wt_db'
# make it list of user ids
# flyb1z0n = 166219758
# jane = 390885313
ALLOWED_USERS = [166219758, 390885313]

[production]
DB_URL = 'mongodb'
