[default]
DB_URL = 'localhost'
DB_PORT = 27017
DB_NAME = 'wt_db'
# make it list of user ids
# flyb1z0n = 166219758
# jane = 390885313
ALLOWED_USERS = [390885313]
MAX_TEXT_SIZE = 100 #symbols
MAX_DICTIONARY_SIZE = 2000 #words
[production]
DB_URL = 'mongodb'
